### ISSUE TITLE
Bot Folder Expectations 

### ISSUE THREAD

**Issue by WilliamWishart** [AndrioCelos/AIML#1]
I’ve tried running the console instance of the AMIL interpreter but my bot folders don’t seem to have what’s expected. What folder configuration and contents are expected by your solution as it attempts to load the bot?  I assume things aren’t as they were back in 2003 under the old AIML v1.0.

Could you add either a basic set of BOT folders to this repository or describe what the solution expects in the read me?

Many Thanks

William

**Comment by AndrioCelos** [comment]
Hi William. I have added a simple example bot to the repository. I hope it's what you were looking for. You can also see the bots included in the [Program AB](https://code.google.com/archive/p/program-ab/) repository, though they may not work as-is with this solution because of different formats for some of the files.
